server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/people?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: mysql

mybatis:
  mapper-locations: classpath:Mapping/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true